minio:
  image: minio/minio:latest
  container_name: minio
  restart: unless-stopped
  ports:
    - "9000:9000" # API
    - "9001:9001" # Console
  environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER} # admin username
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD} # admin password
  volumes:
    - /var/lib/minio:/data # Storage for minio. CHANGE IF NEEDED!
  command: server /data --console-address ":9001"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
