postgres:
  image: postgres:${POSTGRES_VERSION} # support 14, 15, 16, latest, ...
  container_name: postgres
  restart: unless-stopped
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
  user: ${POSTGRES_GUID} # e.g. 999:999，UID:GID for postgres user
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: postgres
    POSTGRES_INITDB_ARGS: "--data-checksums"
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
    interval: 10s
    timeout: 5s
    retries: 5
