redis:
  image: redis
  container_name: redis
  restart: unless-stopped
  ports:
    - "6379:6379"
  volumes:
    - /var/lib/redis/data:/data
  command: redis-server --requirepass ${REDIS_PASSWORD}
  user: ${REDIS_GUID} # e.g. 999:999，UID:GID for redis user
  healthcheck:
    test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    interval: 10s
    timeout: 5s
    retries: 5
